name : test by SonarCloud
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up JDK 11
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven cloud
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=javareachabilityplayground-test -Dsonar.organization=javareachabilityplayground-test -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
